# Generated by Django 3.1 on 2021-04-28 12:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LAN', 'LAN'), ('WAN', 'WAN'), ('related organizations', 'related organizations')], max_length=50)),
                ('inttype', models.CharField(choices=[('physical', 'physical'), ('VLAN', 'VLAN')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('mask', models.CharField(choices=[('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=2)),
                ('hostname', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('company', models.CharField(max_length=200, verbose_name='Company name')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Organization',
            },
        ),
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('devicemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.devicemodel')),
                ('sitename', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('main.devicemodel', models.Model),
        ),
    ]
