# Generated by Django 3.1 on 2021-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='devicemodel_ptr',
        ),
        migrations.DeleteModel(
            name='DeviceModel',
        ),
        migrations.DeleteModel(
            name='SiteModel',
        ),
    ]
