# Generated by Django 3.1 on 2021-05-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210501_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='jsonform',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
