# Generated by Django 3.1 on 2021-05-02 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_organizationmodel_jsonform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationmodel',
            old_name='jsonform',
            new_name='yamldata',
        ),
    ]
